### ISSUE TITLE
Addon and Compats Master TODO List

### ISSUE THREAD

**Issue by creatorfromhell** [Ghost-chu/QuickShop-Hikari#1756]
- [x] Dominion https://github.com/ColdeZhang/Dominion
- [x] FabledSkyblock https://github.com/craftaro/FabledSkyBlock?tab=readme-ov-file
- [x] EnchantsSquared https://github.com/Athlaeos/EnchantsSquaredRewritten
- [x] IridiumSkyblock
- [x] HuskTowns
- [x] Prevent making the power cell a shop in Ultimate Claims https://github.com/Songoda-Plugins/UltimateClaims
- [x] Pl3xmap https://github.com/granny/Pl3xMap/wiki/Pl3xMap-API
- [x] Quest Required to buy/sell item, and to create shop
     - [x] Quest by Pika

**Comment by SrBedrock** [comment]
[SuperiorSkyblock2](https://github.com/BG-Software-LLC/SuperiorSkyblock2) ?

Edit: Already exist. 😭

**Comment by ghost** [comment]
Support Oraxen items https://github.com/oraxen/oraxen
Support Dominion https://github.com/ColdeZhang/Dominion

**Comment by creatorfromhell** [comment]
> Support Oraxen items https://github.com/oraxen/oraxen Support Dominion https://github.com/ColdeZhang/Dominion

Oraxen support won't be added due to the current situation with the plugin.

**Comment by creatorfromhell** [comment]
Update:

AreaShop maven isn't active anymore....
FabledSkyblock wiki is M.I.A.

**Comment by creatorfromhell** [comment]
FabledSkyBlock in place, minus waiting on seeing how to determine what chunks belong to what island as their API doesn't have an obvious method for this.

**Comment by creatorfromhell** [comment]
Dominion in place.

**Comment by w1th0utme** [comment]
support nexo https://repo.nexomc.com (https://docs.nexomc.com/)

**Comment by Skizzles** [comment]
Support HuskTowns? https://www.spigotmc.org/resources/husktowns-1-17-1-21-towny-style-claims-customizable-easy-to-use-works-cross-server.92672/

**Comment by Mithranduil** [comment]
Would be really nice to add Support for IridiumSkyBlock (https://www.spigotmc.org/resources/iridium-skyblock-1-13-1-21-5.62480/updates)

**Comment by BrailleBennett** [comment]
Prevent making the power cell a shop in Ultimate Claims
https://github.com/Songoda-Plugins/UltimateClaims

**Comment by Zhythero** [comment]
https://modrinth.com/plugin/simpleclaimsystem pls. TY

**Comment by creatorfromhell** [comment]
> https://modrinth.com/plugin/simpleclaimsystem pls. TY

Added in the latest snapshot build. Their API is very limited, so the functionality of the compat module is too.

**Comment by creatorfromhell** [comment]
Removed CMI Ender Chests.. will wait until their jitpack is more stable. as their jitpack has been giving issues.

**Comment by creatorfromhell** [comment]
Removed HuskSync as there isn't a practical reason to make a compat for it.

**Comment by creatorfromhell** [comment]
Removed AreaShop as their maven is no longer online.

**Comment by creatorfromhell** [comment]
EnchantsSquared should be compatible now with the changes made for enchants checking for valid vanilla ones, and the paper deserialization/serialization.

**Comment by creatorfromhell** [comment]
Removed BetonQuest as their API isn't very conducive to what I want to do.

**Comment by creatorfromhell** [comment]
Completed Addon for Quests by Pika

**Comment by YuanYuanOwO** [comment]
https://github.com/Xiao-MoMi/craft-engine
CE support request from community

https://github.com/Xiao-MoMi/craft-engine/pull/398/commits/89df1b4c256b9ef1734914a8347a2ffdb6ecd7ba
done

**Comment by creatorfromhell** [comment]
- Pl3xMap Addon initial release completed.
- Removed WildChests as there doesn't seem to be a lot in the form of compatibility needs.

**Comment by James-P-Bennett** [comment]
* Submitted a PR to implement Squaremap support
https://github.com/QuickShop-Community/QuickShop-Hikari/pull/2176
